/**
 * The canonical origin for the site.
 *
 * Every absolute URL the app emits — canonicals, OG images, sitemap entries,
 * JSON-LD `@id`s — resolves from here, so there is exactly one line to change
 * when a custom domain is registered.
 *
 * Resolution order:
 *   1. `NEXT_PUBLIC_SITE_URL` — set this in Vercel once a real domain is live.
 *   2. `VERCEL_PROJECT_PRODUCTION_URL` — the production hostname Vercel injects
 *      into every deployment, so preview builds resolve to themselves rather
 *      than to a hard-coded origin.
 *   3. The deployment literal, for local `bun dev`.
 *
 * Never carries a trailing slash: callers build paths as `${SITE_URL}/about`.
 */
export const SITE_URL = (
  process.env.NEXT_PUBLIC_SITE_URL ||
  (process.env.VERCEL_PROJECT_PRODUCTION_URL
    ? `https://${process.env.VERCEL_PROJECT_PRODUCTION_URL}`
    : "https://desmark-twintra.vercel.app")
).replace(/\/+$/, "");

/** Absolute URL for a root-relative path. `absoluteUrl("/about")`. */
export function absoluteUrl(path: string): string {
  return `${SITE_URL}${path.startsWith("/") ? path : `/${path}`}`;
}

/**
 * The site-wide social card, generated by `src/app/opengraph-image.tsx`.
 *
 * A page that declares its own `openGraph` block REPLACES the parent's rather
 * than merging into it, so any route with custom OG data must pass this
 * explicitly or it ships a card with no image.
 */
export const OG_IMAGE = {
  url: `${SITE_URL}/opengraph-image`,
  width: 1200,
  height: 630,
  alt: "Desmark Twintra LLP — Global Trade Excellence",
};
